import images from '../assets';

const carList = [
  { name: 'Koenigsegg', type: 'Sport', people: 2, image: images.koenigsegg, price: 99.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 0, subtitle: 'Safety and comfort while driving a futuristic and elegant sports car' },
  { name: 'Nissan GT - R', type: 'SUV', people: 4, image: images.nissan, price: 89.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'Rolls-Royce', type: 'Hackback', people: 4, image: images.rollsRoyce, price: 109.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'Rolls-Royce', type: 'Hackback', people: 4, image: images.rollsRoyce, price: 109.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'Rolls-Royce', type: 'Hackback', people: 4, image: images.rollsRoyce, price: 109.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'Rolls-Royce', type: 'Hackback', people: 4, image: images.rollsRoyce, price: 109.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 8 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 7 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 6 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 5 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 4 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 3 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 2 },
  { name: 'All New Rush', type: 'Coupe', people: 2, image: images.allNewRush, price: 79.00, description: 'NISMO has become the embodiment of Nissan\'s outstanding performance, inspired by the most unforgiving proving ground, the "race track".', text: 'Sports car with the best design and acceleration', id: 1 },
];

export default carList;
